### ISSUE TITLE
MPLAB IPE fails to upload hex

### ISSUE THREAD

**Issue by mygnu** [kiffie/pic32-rs#2]
Hi, I'm really new to PIC or Microcontrollers in general, I have wired up a PIC32MX270F256B, 
copied the ld file for MX270 over to the blinky example,
updated the config with `rustflags = ["-C", "link-arg=-T32MX270F256B_procdefs.ld"]` 
I get the following error.

I'm on linux if that matters

```
*****************************************************

Connecting to MPLAB PICkit 3...

Currently loaded firmware on PICkit 3
Firmware Suite Version.....01.56.09
Firmware type..............PIC32MX
Target voltage detected
Target device PIC32MX270F256B found.
Device ID Revision = A2
Loading code from /home/mygnu/Projects/pic32-rs/examples/blinky/blinky.hex...
Warning: /home/mygnu/Projects/pic32-rs/examples/blinky/blinky.hex contains code that is located at addresses that do not exist on the PIC32MX270F256B.
Code incompletely loaded starting at 0x9D000000 (0x3D4).
2021-08-20 11:17:58 +0100 - Hex file loaded successfully.
2021-08-20 11:18:06 +0100 - Programming...


Device Erased...

Programming...

The following memory area(s) will be programmed:
MPLAB's memory is blank so no programming operation was attempted.
2021-08-20 11:18:10 +0100 - Programming complete
```

**Comment by kiffie** [comment]
The problem is that ```objcopy``` produces hex files having virtual addresses as opposed to physical addresses. It seems that the Microchip programmer can handle hex files having physical addresses only. I did not experience this problem because I use a different programming tool: [pic32prog](https://github.com/sergev/pic32prog).

If you generate the hex file using the tool ```xc32-bin2hex```, which is part of the XC32 compiler (I tried it with xc32 release 1.43), you should obtain a hex file having physical addresses that can be programmed with ```ipecmd```.

    cargo build --release
    xc32-bin2hex target/mipsel-unknown-none/release/blinky

I managed to flash a PIC32MX270F256B using the Snap programming hardware.

I hope this helps.

**Comment by mygnu** [comment]
Thanks for the reply, I will try it out tonight, I'm using pickit3 so the pic32prog might not work. I'm also planning on writing an article about setting things up and using this crate for noobs like me.

**Comment by mygnu** [comment]
Thanks it worked, closing this for now

**Comment by kiffie** [comment]
Great to read that it works. Maybe, I should document this in one of the readme files. Looking forward to your planned howto article.
